cargo-features = ["rename-dependency"]

[package]
name = "seabird"
version = "0.1.0"
authors = ["Kaleb Elwert <belak@coded.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
irc = { package = "simple-irc", git = "https://github.com/belak/simple-irc-rs" }
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros", "net", "rt-core", "rt-threaded", "stream", "sync", "time"] }
