[package]
name = "seabird"
version = "0.1.0"
authors = ["Kaleb Elwert <belak@coded.io>"]
edition = "2018"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
atty = "0.2"
bytes = "0.5"
dotenv = "0.15"
futures = "0.3"
irc = { package = "simple-irc", version = "0.3.1" }
log = "0.4"
native-tls = "0.2"
pretty_env_logger = "0.4"
regex = "1.3"
reqwest = { version = "0.10", features = ["json"] }
thiserror = "1.0"
tokio = { version = "0.2", features = ["io-util", "blocking", "macros", "tcp", "rt-core", "rt-threaded", "stream", "sync", "time"] }
tokio-tls = "0.3"
tokio-util = { version = "0.2", features = ["codec"] }

# Plugin dependencies
barrel = { version = "0.6", features = ["pg"] }
tokio-postgres = "0.5"
rand = "0.7"

# In order to get refinery working with barrel, for now we need to use the
# version from git.
refinery = { git = "https://github.com/rust-db/refinery", features = ["tokio-postgres"] }
