[package]
name = "seabird-plugin-bundle"
version = "0.1.0"
authors = ["Kaleb Elwert <belak@coded.io>"]
edition = "2018"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
bytes = "0.5"
dotenv = "0.15"
futures = "0.3"
log = "0.4"
maplit = "1.0"
pretty_env_logger = "0.4"
tokio = { version = "0.2", features = ["macros", "rt-core", "stream", "sync", "time"] }

# Plugin dependencies
http = "0.2"
itertools = "0.9"
rand = "0.7"
regex = "1.3"
reqwest = { version = "0.10", features = ["gzip", "json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["runtime-tokio", "macros", "migrate", "postgres", "offline"] }
time = "0.2"
tokio-postgres = "0.5"
trust-dns-resolver = { version = "0.19", features = ["tokio-runtime"] }
url = "2.1"
git-version = "0.3"
unicode-segmentation = "1.6"

# Client library
seabird = "0.1.0-alpha.4"
