[package]
name = "seabird"
version = "0.1.0"
authors = ["Kaleb Elwert <belak@coded.io>"]
edition = "2018"

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
atty = "0.2"
bytes = "0.5"
dotenv = "0.15"
futures = "0.3"
irc = { package = "simple-irc", version = "0.3.1" }
log = "0.4"
native-tls = "0.2"
pin-project = "0.4"
pretty_env_logger = "0.4"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros", "tcp", "rt-core", "rt-threaded", "stream", "sync", "time"] }
tokio-tls = "0.3"

# Plugin dependencies
barrel = { version = "0.6", features = ["pg"] }
quick-xml = "0.17"
rand = "0.7"
regex = "1.3"
reqwest = { version = "0.10", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
time = "0.2"
tokio-postgres = "0.5"
trust-dns-resolver = { git = "https://github.com/belak/trust-dns", branch = "caa-as-str", version = "0.19", features = ["tokio-runtime"] }

# In order to get these packages working properly, we need to use the versions
# from git.
refinery = { git = "https://github.com/rust-db/refinery", features = ["tokio-postgres"] }
