[package]
name = "seabird"
version = "0.1.0"
authors = ["Kaleb Elwert <belak@coded.io>"]
edition = "2018"

[features]
default = ["db"]
db = ["diesel", "diesel_migrations"]

[dependencies]
# Core dependencies
anyhow = "1.0"
async-trait = "0.1"
bytes = "0.5"
dotenv = "0.15"
futures = "0.3"
irc = { package = "simple-irc", version = "0.3" }
native-tls = "0.2"
regex = "1.3"
reqwest = { version = "0.10", features = ["json"] }
thiserror = "1.0"
tokio = { version = "0.2", features = ["io-util", "blocking", "macros", "tcp", "rt-core", "rt-threaded", "stream", "sync", "time"] }
tokio-tls = "0.3"
tokio-util = { version = "0.2", features = ["codec"] }

# Plugin dependencies
diesel = { version = "1.4", features = ["postgres", "r2d2"], optional = true }
diesel_migrations = { version = "1.4", optional = true }
rand = "0.7"
