version: '3.7'

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: seabird
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seabird
    ports:
      - '5432:5432'

volumes:
  postgres-data: {}
